query: |
  subscription ($id: Int!) {
    test(where: {id: {_eq: $id}}) {
      id
      name
    }
  }
timePeriod: 2
variables:
  id: '1'
headers:
  X-Hasura-Admin-Secret: ""
template:
  range:
    start: 1
    end: 10
  headers: []
  variables:
    - id