query: 'subscription($id: Int) { test(where: {id: {_eq: $id}}) { id name } }'
timePeriod: 60
variables:
  id: '1'
headers:
  X-Hasura-Role: admin
template:
  range:
    start: 1
    end: 600
  headers: []
  variables:
  - id
