query: |
  subscription ($id: Int!) {
    test(where: {id: {_eq: $id}}) {
      id
      name
    }
  }
timePeriod: 10
variables:
  id: '1'
headers:
  X-Hasura-Role: admin
template:
  range:
    start: 1
    end: 1000
  headers: []
  variables:
    - id